# Generated by Django 5.1.5 on 2025-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_filemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=30)),
                ('Genre', models.CharField(max_length=30)),
                ('Published_Date', models.DateField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Books/')),
            ],
        ),
    ]
