# Generated by Django 5.1.5 on 2025-02-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.author'),
        ),
    ]
