# Generated by Django 5.1.5 on 2025-02-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_author_alter_bookmodel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='Genre',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='Genre',
            field=models.ManyToManyField(to='app1.genre'),
        ),
    ]
